import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface MealEntry {
    created_at: string;
    meal_slot: string;
    total_calories: number;
    total_protein: number;
    total_carbs: number;
    total_fat: number;
    analyzer_json?: any;
}

interface AnalyticsData {
    meals: MealEntry[];
    profile: {
        full_name?: string;
        target_calories: number;
        protein_g: number;
        carbs_g: number;
        fat_g: number;
    };
    dateRange: {
        start: Date;
        end: Date;
    };
}

export async function exportAnalyticsToPDF(data: AnalyticsData) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(16, 185, 129); // Primary green
    doc.text('CalorieWise Analytics Report', pageWidth / 2, 20, { align: 'center' });

    // User info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`User: ${data.profile.full_name || 'User'}`, 14, 35);
    doc.text(
        `Period: ${format(data.dateRange.start, 'MMM d, yyyy')} - ${format(data.dateRange.end, 'MMM d, yyyy')}`,
        14,
        42
    );

    // Summary Statistics
    const totalCalories = data.meals.reduce((sum, m) => sum + (m.total_calories || 0), 0);
    const totalProtein = data.meals.reduce((sum, m) => sum + (m.total_protein || 0), 0);
    const totalCarbs = data.meals.reduce((sum, m) => sum + (m.total_carbs || 0), 0);
    const totalFat = data.meals.reduce((sum, m) => sum + (m.total_fat || 0), 0);
    const avgCalories = Math.round(totalCalories / data.meals.length);

    doc.setFontSize(14);
    doc.text('Summary Statistics', 14, 55);

    doc.setFontSize(10);
    const summaryData = [
        ['Total Meals Logged', data.meals.length.toString()],
        ['Average Daily Calories', `${avgCalories} kcal`],
        ['Total Protein', `${Math.round(totalProtein)}g`],
        ['Total Carbs', `${Math.round(totalCarbs)}g`],
        ['Total Fat', `${Math.round(totalFat)}g`],
        ['Daily Calorie Target', `${data.profile.target_calories} kcal`],
    ];

    autoTable(doc, {
        startY: 60,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: [16, 185, 129] },
    });

    // Meal Log Table
    doc.addPage();
    doc.setFontSize(14);
    doc.text('Detailed Meal Log', 14, 20);

    const mealData = data.meals.map(meal => [
        format(new Date(meal.created_at), 'MMM d, yyyy'),
        meal.meal_slot || 'N/A',
        meal.total_calories?.toString() || '0',
        `${meal.total_protein?.toFixed(1) || '0'}g`,
        `${meal.total_carbs?.toFixed(1) || '0'}g`,
        `${meal.total_fat?.toFixed(1) || '0'}g`,
    ]);

    autoTable(doc, {
        startY: 25,
        head: [['Date', 'Meal', 'Calories', 'Protein', 'Carbs', 'Fat']],
        body: mealData,
        theme: 'striped',
        headStyles: { fillColor: [16, 185, 129] },
        styles: { fontSize: 8 },
    });

    // Goals Progress
    doc.addPage();
    doc.setFontSize(14);
    doc.text('Goals Progress', 14, 20);

    const calorieProgress = Math.round((avgCalories / data.profile.target_calories) * 100);
    const proteinProgress = Math.round((totalProtein / data.meals.length / data.profile.protein_g) * 100);

    const goalsData = [
        ['Calorie Goal', `${calorieProgress}%`, avgCalories >= data.profile.target_calories ? 'On Track' : 'Below Target'],
        ['Protein Goal', `${proteinProgress}%`, proteinProgress >= 90 ? 'On Track' : 'Below Target'],
    ];

    autoTable(doc, {
        startY: 25,
        head: [['Goal', 'Progress', 'Status']],
        body: goalsData,
        theme: 'grid',
        headStyles: { fillColor: [16, 185, 129] },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Generated by CalorieWise on ${format(new Date(), 'MMM d, yyyy')} - Page ${i} of ${pageCount}`,
            pageWidth / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: 'center' }
        );
    }

    // Save the PDF
    const filename = `CalorieWise_Analytics_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
    doc.save(filename);

    return filename;
}

export async function exportMealsToPDF(meals: MealEntry[], userProfile: any) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(16, 185, 129);
    doc.text('CalorieWise Meal Log', pageWidth / 2, 20, { align: 'center' });

    // User info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`User: ${userProfile.full_name || 'User'}`, 14, 35);
    doc.text(`Export Date: ${format(new Date(), 'MMM d, yyyy')}`, 14, 42);

    // Meal table
    const mealData = meals.map(meal => {
        const foods = meal.analyzer_json?.food || [];
        const foodNames = foods.map((f: any) => f.name).join(', ') || 'N/A';

        return [
            format(new Date(meal.created_at), 'MMM d, HH:mm'),
            meal.meal_slot || 'N/A',
            foodNames.substring(0, 40) + (foodNames.length > 40 ? '...' : ''),
            meal.total_calories?.toString() || '0',
            `${meal.total_protein?.toFixed(1) || '0'}g`,
        ];
    });

    autoTable(doc, {
        startY: 50,
        head: [['Date/Time', 'Meal', 'Foods', 'Calories', 'Protein']],
        body: mealData,
        theme: 'striped',
        headStyles: { fillColor: [16, 185, 129] },
        styles: { fontSize: 9 },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Generated by CalorieWise - Page ${i} of ${pageCount}`,
            pageWidth / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: 'center' }
        );
    }

    const filename = `CalorieWise_Meals_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
    doc.save(filename);

    return filename;
}
